# Generated by Django 2.2 on 2019-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='circle_id',
            field=models.IntegerField(),
        ),
    ]
