# Generated by Django 2.2 on 2019-04-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_user_circles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='circle_id',
        ),
    ]
