# Generated by Django 2.2 on 2019-04-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_auto_20190428_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='createdBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='username+', to=settings.AUTH_USER_MODEL),
        ),
    ]
