# Generated by Django 2.2 on 2019-04-28 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0010_auto_20190428_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(related_name='circles', to=settings.AUTH_USER_MODEL),
        ),
    ]
